rails_tutorials: "https://www.railstutorial.org/"
michael: "https://www.michaelhartl.com/"
news: "https://news.railstutorial.org/"

learn_enough: "https://www.learnenough.com/"
rails_book: "https://www.railstutorial.org/book"
screen: "https://screencasts.railstutorial.org/"
rails: "https://rubyonrails.org/"

contact: "https://www.railstutorial.org/contact"
help: "https://www.railstutorial.org/help"

user:
  name_max: 50
  email_max: 255
  email_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  pass_min: 6
